<div class="contact__container row">
	<!-- Name, Title, Email, Resume -->
	<p class="contact--title">Alexander Ashie - 3D Artist</p>
	<p class="contact--email">alexanderashie@gmail.com</p>
	</br></br>
	<p class="contact--resume">Download Resume</p>
	
	<!-- Skills, Projects, Experience, Education -->
	<p class="contact--info">Skills:</p>
	<hr>
	<ul>
		<li><p class="contact--list">[Modeling] 
		<span font-style="italic">ZBrush, Maya, TopoGun, 3D Coat</span> - Strong understanding of high-to-low workflow:</p></li>
		<ul>
		<li><p class="contact--listitem">High-poly sculpting, retopology, and edge flow for deformation, LOD's</p></li>
		<li><p class="contact--listitem">Mesh optimization to meet specific polycounts, organic and hard Surface</li></p>
		</ul>

		<li><p class="contact--list">[Texturing] 
			<span font-style="italic">xNormal, Photoshop, Substance Designer/Painter</span> - UV's, baking, and PBR packages:</p></li>
		<ul>
		<li><p class="contact--listitem">Mastery of efficient UV layouts, baking relevant maps (AO, Normal, Curvature, etc.)</p></li>
		<li><p class="contact--listitem">Utilization of latest PBR texturing packages (Albedo, Metallic, Roughness, etc.)</li></p>
		</ul>

		<li><p class="contact--list">[Engines] 
			<span font-style="italic">Unreal Engine 4, Unity 5, Marmoset Toolbag 2</span> - Strong understanding of current industry game engines:</p></li>
		<ul>
		<li><p class="contact--listitem">Utilization of Unreal Engine 4, Unity 5, to integrate assets into a project</p></li>
		<li><p class="contact--listitem">Using an engine to create the final asset: importing meshes, creating and using custom collision, LOD setups, node-based material editors, lighting, particle effects, etc.</li></p>
		</ul>
	</ul>
	</br>

	<p class="contact--info">Projects:</p>
	<hr>
	<ul>
		<li><p class="contact--list">["Rise of the Restless", 2015] 
		<span font-style="italic">Art Lead - </span>Shawnee State University, Senior Project</p></li>
		<ul>
		<li><p class="contact--listitem">Direct workflow and delegate tasks to other team members, serve as a mentor to the team, troubleshooting, and problem-solving</p></li>
		<li><p class="contact--listitem">Bridge the communication gap between the art team and programming team, attend lead meetings, prioritize tasks, oversee asset integration</li></p>
		<li><p class="contact--listitem">Also responsible for: Character Art, Particle Effects, GUI, and Motion Capture Performance</li></p>
		</ul>
	</ul>
	</br>

	<p class="contact--info">Work Experience:</p>
	<hr>
	<ul>
		<li><p class="contact--list">[September 2015 - December 2015] 
		<span font-style="italic">Freelance 3D Artist - </span>Portsmouth, Ohio</p></li>
		<ul>
		<li><p class="contact--listitem">Work with client on a given loose concept to create props via sculpting in ZBrush for printing/molding manufacturing</p></li>
		<li><p class="contact--listitem">Communicate to ensure product meets technical specifications to allow for a smooth manufacturing process</li></p>
		</ul>
		<li><p class="contact--list">[2013 - December 2015] 
		<span font-style="italic">Lab Technician/Studio Monitor, Vern Riffe Center for the Arts - </span>Shawnee State University - Portsmouth, Ohio</p></li>
		<ul>
		<li><p class="contact--listitem">Maintenance of studio machines and printers</p></li>
		<li><p class="contact--listitem">Communicate with FDPA Chair, Faculty, and IT Department to coordinate and address all hardware and software related issues</li></p>
		<li><p class="contact--listitem">Ensure machines are in working order, Windows and OSX administrative rights to install and license software as well as resolve issues</li></p>
		<li><p class="contact--listitem">Monitor classroom studios, and tutor students for Gaming/Digital classes</li></p>
		</ul>
	</ul>
	</br>

	<p class="contact--info">Education:</p>
	<hr>
	<ul>
		<li><p class="contact--list">[2011 - 2015] 
		<span font-style="italic">Shawnee State University - </span>Portsmouth, Ohio</p></li>
		<ul>
		<li><p class="contact--listitem">Bachelor of Fine Arts - Gaming and Simulation Design</p></li>
		</ul>
	</ul>
	</br>

	<p class="contact--info">References</p>
	<hr>
	<ul>
		<li><p class="contact--listitem">References available upon request</p></li>
	</ul>
	</br></br></br>
	
	<!-- Contact form -->
	<p class="contact--info">Contact:</p>
	<hr>
	<form>
	    <div class="contact--list">Name:</div>
	    <input type="text" name="name" size="30"></br>
	    <div class="contact--list">E-mail Address:</div>
	    <input type="email" name="email" size="40"></br>
	    <div class="contact--list">Message:</div>
	    <textarea name="message" rows="5" cols="65"></textarea></br></br>
	    <input type="submit" value="Submit">
	</form>


</div>